name: bentoml-server

services:

  bentoml-server:

    build:
      context: ../..
      dockerfile: infrastructure/bentoml_server/Dockerfile
      args:
        PYTHON_VERSION: 3.12.8

    ports:
      - 3000:3000


    volumes:
      - ${USERPROFILE}/bentoml:/root/bentoml