services:

  minio:
    image: minio/minio:latest

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}


    ports:
      - 9000:9000
      - 9001:9001


    volumes:
      - minio_data:/minio_data

    command: server /minio_data --console-address ":9001"


  mlflow:
    image: ghcr.io/mlflow/mlflow:latest


    ports: 
      - 5000:5000

    command: mlflow ui --host "0.0.0.0" --default-artifact-root "s3://mlflow"

    volumes:
      - mlflow_data:/mlflow_data


volumes:
  minio_data:
  mlflow_data: