name: server

services:
  server:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - 5001:5001
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    command: /bin/bash -c "pip install --upgrade pip && pip install boto3 && mlflow models serve -m models:/RandomForestClassifier/1 --host 0.0.0.0 --no-conda -p 5001"
    networks:
      - shared_network

networks:
  shared_network:
    external: true

