name: main

services:

  minio:
    image: minio/minio:latest

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    ports:
      - 9000:9000
      - 9001:9001

    volumes:
      - minio_data:/minio_data

    command: server /minio_data --console-address ":9001"

    networks:
      - shared_network




  mlflow:
  
    image: ghcr.io/mlflow/mlflow:latest

    ports: 
      - 5000:5000

    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_S3_ENDPOINT_URL: ${MLFLOW_S3_ENDPOINT_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}


    command: /bin/bash -c  "pip install boto3 && mlflow ui --host 0.0.0.0 --default-artifact-root s3://mlflow"

    volumes:
      - mlflow_data:/mlflow_data

    networks:
      - shared_network





volumes:
  minio_data:
  mlflow_data:

networks:
  shared_network:
    external: true